# docker-compose.yml

version: "3"

services:

  webapp:
    build: .
    ports:
      - "8080:8080"
    labels:
      - "webapp=varlogs"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
